target-version = "py310"

line-length = 79

exclude = ["infra/migrations/*"]

[lint]
extend-select = [
  "UP",  # pyupgrade   # pydocstyle
]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "tab"
